services:
  statistics-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - shared-network

networks:
  shared-network:
    external: true