version: '3.1'

services:

  assets-management-db:
    image: postgres:16-alpine
    environment:
        POSTGRES_USER: assets_user
        POSTGRES_PASSWORD: assets_user
        POSTGRES_DB: assets_management
        PGDATA: /data/postgres
    volumes:
        - assets-management-db:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - assets-network
    restart: unless-stopped


  assets-management-api:
    build: .
    restart: always
    ports:
      - "9042:9042"
    environment:
      - SPRING_PROFILES_ACTIVE=psql
      - SPRING_DATASOURCE_URL=jdbc:postgresql://assets-management-db:5432/assets_management
    depends_on:
      - assets-management-db
    networks:
      - assets-network
      - shared-network

volumes:
    assets-management-db:

networks:
    assets-network:
      driver: bridge
    shared-network:
      external: true

