services: 
  web-gateway:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "9040:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - shared-network
    
networks:
  shared-network:
    external: true