version: '3.9'

services:
  web-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9041:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - shared-network

networks:
  shared-network:
    external: true