name: Docker Image Tracking CI

on:
  push:
    branches: [ "main" ]

jobs:

  push-tracking:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Package TrackingApi with Maven
        working-directory: ./TrackingManagementApi
        run: |
          mvn package
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./TrackingManagementApi
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tracking-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/tracking-api:latest
